name: 'Terraform-destroy'
 
on: 
  push:
    branches:
    - main
  #pull_request:  
  workflow_dispatch:  
  
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 'Terraform Plan Destroy'
      uses: hashicorp/terraform-github-actions@master
      with:
         tf_actions_version: latest
         tf_actions_subcommand: 'plan'
         args: '-destroy -out=./destroy-plan'
    - name: 'Terraform Apply Destroy'
      uses: hashicorp/terraform-github-actions@master
      with:
            tf_actions_version: latest
            tf_actions_subcommand: 'apply'  
            args: './destroy-plan'

